title: Tantrasya
tagline: A Journey into the Esoteric, Occult and Quantum Realms
description: Insights into healing, tantra, karma, and the sacred geometry of existence.
url: ""  # Will be set later based on domain
baseurl: ""  # Leave blank for root or /blog for subpath
remote_theme: cotes2020/jekyll-theme-chirpy
lang: en
timezone: Asia/Kolkata

author:
  name: Saurhin Parikh
  bio: Seeker, Healer, Occultist
  email: ""

logo: /assets/img/profile.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-tagging
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Saurhin
